### ISSUE TITLE
Guidance on production AKS cluster upgrade

### ISSUE THREAD

**Issue by nitinkhandelwal26** [mspnp/aks-secure-baseline#105]
Hello Team,

Currently, we are using 1.18, and 1.19 will be GA by end of this month.
Any guidance or considerations on the AKS cluster upgrade in a production environment? 
Any automation possible using flux on this part?

**Comment by ckittel** [comment]
The general process is well described @ <https://docs.microsoft.com/en-us/azure/aks/upgrade-cluster> -- I would suggest considering making use use of the node surge feature.  While it's still in preview, its been well received by customers and I hear it's on the short list to remove from preview soon.

We haven't begun analyzing 1.19 yet WRT the baseline here.  So I don't have anything specific to say at this time.

However here are some highlights of general 1.19 things that I'm aware of

* the built-in kubernetes dashboard will be gone (but if you're following this baseline, that feature is already disabled -- might need to remove that configuration from the ARM template -- but guessing it will just ignore it). I don't think we're supporting the new built in v2 version, IIRC.
* you might see additional warnings now around some of your resources defined with `beta` API versions when there are new production versions available.  This reminds you to move out of the beta definitions and into the production versions.
* The pod/container `securityContext` now has a `seccompProfile` that you can add directly to describe your secure computing mode requirements (this used to be done via annotations in the past)
* 1.19 is changing how AzureDisk CSI drivers are handled -- for the better.  If you don't have storage in your cluster (first off, great!), then this isn't applicable.  But if you do, there are some core changes you need to make for the `kubernetes.io/azure-disk` storage class.

General k8s 1.18 -> 1.19 [changes are here](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.19.md#whats-new-major-themes) -- but again, I don't have any specific knowledge for AKS 1.19 wrt updates yet -- other than what is documented in my first link above.

**Comment by nitinkhandelwal26** [comment]
Thank you so much for the guidance @ckittel , Do you have any plan to have automation to achieve this in your architecture roadmap?

**Comment by ckittel** [comment]
We don't currently have any automation plan that I'm aware of. With Service Fabric, we were able to apply updates automatically because we strived hard for backwards compatibility between minor versions -- and even though we controlled that end-to-end, we still recommended manual upgrades there as well for production.  With Kubernetes, at its core, being managed up stream, and the variability of workloads (3rd-party OSS, etc) that are running in customer clusters, I would imagine it's very unsafe for us to automatically roll forward kubernetes versions.  Rolling to a new core k8s version (and therefor AKS version) is something you need to test/validate against all components you have working in your cluster. What if you don't have enough available IP space to add new nodes? What if that 3rd-party security DeamonSet you used for compliance reasons was referencing a now-removed k8s API? etc.  Luckily, when you have tested your cluster and you do you want to roll forward, the command we have for you to do this takes care of a lot of the heavy lifting of the actual process. :)

Likewise, we'll be doing the same evaulation on the baseline here.  Making sure our features still work as expected and/or leveraging new features as they are available.

**Comment by nitinkhandelwal26** [comment]
Thank you @ckittel for providing valuable insight.

**Comment by ckittel** [comment]
Hey there @nitinkhandelwal26 -- the PR for 1.19 is now out there -- if you're interested to see the changes.  The body talks about the changes we made to the baseline to account for 1.19 features.  I'm not aware of any "breaking changes" (so to speak) -- all of the changes we made were more quality of life and just using new features.

The PR so you can see the specific changes: #118
