### ISSUE TITLE
Can we use same certificate on both Ingress Controller and Application Gateway

### ISSUE THREAD

**Issue by nitinkhandelwal26** [mspnp/aks-secure-baseline#145]
Hello Team,

Can we have the same certificate for both the ingress controller and application gateway?
like portal.abc.com rather then currently portal.abc.com for app gateway & *.aks-ingress.abc.com for ingress controller
and api.abc.com instead of api.abc.com for app gateway & *.aks-ingress.abc.com

This way also traffic at every hop is secure as well. 
Can we have multiple ingress controller services pointing to the same internal load balancer IP consuming different certificates from AKV secret store?
@ckittel  Request you to Please advise here.

**Comment by nitinkhandelwal26** [comment]
Requirement here is network security team want to replace app gateway to checkpoint firewall, and checkpoint does not support different Certificate for backend.

**Comment by ckittel** [comment]
You're welcome to use the same cert, but it will need to be a wildcard cert. `*.abc.com` and then you'll need a private DNS zone entry for something like `ingress-portal.abc.com` and `ingress-api.abc.com`.

I don't have enough experience with CheckPoint to have any specific on that product. As long as it can serve your compliance needs and is also a WAF, there shouldn't be a problem.  It'll need network line of sight to your internal load balancer fronting your ingress service, and that'll be it.

As for the question of multiple ingress controller services pointing to the same internal load balancer IP question.  If you're using Traefik as your ingress controller, it supports a default certificate for non-SNI traffic and a certificate per host as well for SNI traffic.  That way you don't need to run multiple separate instances of traefik.  It is my understanding that, currently, the identified `loadBalancerIP` cannot be used by more than one resource -- but I might be wrong on that.  I'm not in a good position right now to test that out.

**Comment by nitinkhandelwal26** [comment]
Thank you @ckittel  for your guidance, it is really helpful.

Do you have any recommendation for WAF product which also support binary endpoint in backend pool as App Gateway does not support binary endpoint and checkpoint firewall also don't support it. 

We have KAFKA with binary endpoint with SSL along with AKS in landline zone subscription which needs to be interacted with client system.

**Comment by nitinkhandelwal26** [comment]
Security team is currently exploring F5 load balancer for this functionality because none of the Microsoft products fulfills the requirement.

**Comment by ckittel** [comment]
When you say "binary endpoint" -- that's a term I'm not familiar with.  If this is an Azure Application Gateway question, it might be best fielded by that team.  I can help facilitate that if you can maybe re-express the question differently so I can can understand the scope better to handle "back n forth" on it internally.

**Comment by nitinkhandelwal26** [comment]
Thank @ckittel  for your support.
Currently, the Network team decided to replace App gateway from F5 load balancer and checkpoint firewall.

**Comment by scaswell-hirez** [comment]
> 
> 
> You're welcome to use the same cert, but it will need to be a wildcard cert. `*.abc.com` and then you'll need a private DNS zone entry for something like `ingress-portal.abc.com` and `ingress-api.abc.com`.
> 

Is this still a requirement, and if so can you provide a little more guidance on how to set up the private DNS entries correctly?  My current setup uses the same wildcard cert for both the Application Gateway and the Ingress Controller.  I'm currently having trouble accessing the workload (the health probe returns an unknown status), and I'm curious if this is the reason why?  If so I don't currently understand why adding private DNS entries will resolve this.

**Comment by ckittel** [comment]
The recommendation was to allow your ingress controller to route based on `Host` and also simplified at the same time by only requiring the management and exposure of a single cert. And since these DNS names do not need to be publicly available, a private DNS zone could be used to help hold those DNS records.

**Comment by kamilzzz** [comment]
The certificate part is clear for me (wildcard to simplify management).
Why use private DNS zone and entries like ingress-portal.abc.com and ingress-api.abc.com, though?

Can't portal.abc.com and api.abc.com be mapped to Application Gateway's public IP and then also defined in Ingress YAML definitions as hosts? 
Application Gateway backend can be configured with IP address of internal load balancer and with the default configuration of backend setting it will send original HTTP Host header & SNI values from the client - "By default, Application Gateway does not change the incoming HTTP host header from the client and sends the header unaltered to the backend.".

**Comment by ckittel** [comment]
I don't see why not. We used two certificates to illustrate that there are two configuration points to address, and each point can "look/behave" differently if desired. For example, public facing cert could have long TTL, EV status, non-wildcard, etc. While internal cert may be wildcard, have a different TTL or whatever. They might even be issued by different issuers as one is inside the network. The mTLS feature is what we wanted to highlight because it's commonly used like this. If we overloaded the usage of a single cert, the configuration points would be harder to detect for folks that want separation on concerns (utility) with their certs. Isolated certs can also help if one gets (or needs to become) invalidated, less surface area to tend to. 

As you called out, the backend pool would need to be IP based (honestly not sure how TLS would work like this - it might, don't know) or you'd need a local DNS zone override to make sure that portal.abc.com didn't resolve to the public IP of the gateway.  :)

Let us know what you discover, we can always document alternatives!

**Comment by kamilzzz** [comment]
Sure, thanks for clarification. Separation of concerns perfectly makes sense. Especially when we are talking about enterprise customers :)

I have checked TLS with backend pool configured to be IP based and this is working fine. With hostname override disabled in the backend pool settings, Application Gateway will send Host and SNI header from initial client connection. Traefik is going to receive portal.abc.om as Host and SNI and will be to respond with correct certificate and route correctly based on host.

Application Gateway behaviour regarding SNI and Host headers is somehow described in the documentation - https://learn.microsoft.com/en-us/azure/application-gateway/ssl-overview#sni-differences-in-the-v1-and-v2-sku. However, it wasn't really clear for me whether this setup is going to work or not, until I tested this myself :)
