### ISSUE TITLE
cluster-stamp deployment throws an error about missing vnet

### ISSUE THREAD

**Issue by Mahesh-MSFT** [mspnp/aks-secure-baseline#165]
i am getting following error when running `az deployment group create -g aks-rg -f ./cluster-stamp.json -p targetVnetResourceId=${RESOURCEID_VNET_CLUSTERSPOKE} clusterAdminAadGroupObjectId=${AADOBJECTID_GROUP_CLUSTERADMIN} k8sControlPlaneAuthorizationTenantId=${TENANTID_K8SRBAC} appGatewayListenerCertificate=${APP_GATEWAY_LISTENER_CERTIFICATE} aksIngressControllerCertificate=${AKS_INGRESS_CONTROLLER_CERTIFICATE_BASE64}`

```
Deployment failed. Correlation ID: b8c661c6-2969-4a2f-b63c-37a570db5c6e. {
  "error": {
    "code": "InvalidResourceReference",
    "message": "Resource /subscriptions/<my-sub>/resourceGroups/RG-ENTERPRISE-NETWORKING-SPOKES/providers/Microsoft.Network/virtualNetworks/VNET-SPOKE-BU0001A0008-00 referenced by resource /subscriptions/<my-sub>/resourceGroups/aks-rg/providers/Microsoft.Network/privateEndpoints/nodepool-to-acr was not found. Please make sure that the referenced resource exists, and that both resources are in the same region.",
    "details": [
      {
        "code": "NotFound",
        "message": "Resource /subscriptions/<my-sub>/resourceGroups/RG-ENTERPRISE-NETWORKING-SPOKES/providers/Microsoft.Network/virtualNetworks/VNET-SPOKE-BU0001A0008-00 not found."
      }
    ]
  }
}
```

i can see that `VNET-SPOKE-BU0001A0008-00` exists in RG `rg-enterprise-networking-spokes`. Although, the actual name is `vnet-spoke-BU0001A0008-00` (Note the difference in first two words in lowercase!). Not sure though if this is reason for error. i am not converting lowercase to uppercase anywhere.

any thoughts?

**Comment by ckittel** [comment]
Hey there, sorry you ran into this. We have not seen this before. Were you able to resolve or still blocked on this (I know it's been some time...). Did you by chance change any target regions in your deployment?  Maybe we have a gap in our regional support that didn't apply a region change properly in the ARM templates.

**Comment by learnercrypto** [comment]
Hey Folks, I don't know if I am doing something wrong or cluster-stamp couldn't rum AKS deployment and exit with the below message:
Deployment failed. Correlation ID: f3913046-d719-463e-b373-d20fb2fe940a. {
"code": "ResourceNotFound",
"message": "The Resource 'Microsoft.ContainerService/managedClusters/aks-tgp5w6mq6ev7q' under resource group 'rg-bu0001a0008' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix Activity ID: e18f611e-ec48-426e-850c-dc7385b1e3d6."
}
I assumed the problem is because of limits in Compute-VM for Total Regional vCPUs, It is fixed but yet there is no progress. Could you advise please what is the solution?

**Comment by ckittel** [comment]
Going to close with no update. If there is something more you'd like to address in here, or you feel there is something we can do different in the guidance, please feel free to reopen.  Cheers.
