### ISSUE TITLE
Not able to access https://bicycle.contoso.com

### ISSUE THREAD

**Issue by nitinkhandelwal26** [mspnp/aks-secure-baseline#21]
Deployment is successful, I have created DNS entry but unable to access the website not even by IP.
It throwing 404 error, Any steps to debug the same?

Below is the error:

404 Not Found
Microsoft-Azure-Application-Gateway/v2

**Comment by ferantivero** [comment]
thanks for sharing this @nitinkhandelwal26, 

Please let us check with you whether your Azure Application Gateway is healthy. For this, please go to the `Azure Portal` -> `Azure Application Gateway` -> `Monitoring` -> `Backend Health`

Additionally, please take into account that accessing the website using the IP address will be bit more arduous because Azure Application Gateway needs the host information to properly route the requests.

**Comment by ferantivero** [comment]
@nitinkhandelwal26 it's been a week since we haven't hear from you on this issue. Please let us close this for now. Don't hesitate to reopen it provided you're still facing this problem.
