### ISSUE TITLE
Q: What are the considerations in choosing Traefik ingress controller

### ISSUE THREAD

**Issue by nitinkhandelwal26** [mspnp/aks-secure-baseline#23]
Hi Team,

I have several points which are not clear/explained from the documentation available at aka.ms/architecture/aks-baseline:

Q What are the considerations you took for this case study in choosing the Traefik ingress controller with Azure Application Gateway when we have AGIC available which have integrated WAF?.
 Q: Why you defined workload-level ingress rather than cluster-level ingress? if we define cluster-level ingress then any special considerations do we need to make? - require guidance.

Regards,

**Comment by ferantivero** [comment]
First and foremost thanks for your feedback @nitinkhandelwal26 this is always greatly appreciated. 

Please let us close this asking you to provide the very same feedback at aka.ms/architecture/aks-baseline where we will be able to follow up this item from a more architectural point of view. In this repo you might find more implementation issues, in general.

To conclude please let us tell you in advance, that Azure Application Gateway web traffic load balancer is ready to be integrated with number of Ingress Controllers and Traefik happens to be one them, and a very popular in the Kubernetes Ingress community. That said, this reference implementation can show case them seamlessly working together.

Regarding the workload-level vs cluster-level ingress, it will really depends on your case scenario. In this reference implementation we have a single workload and that's why it is deployed the way it is. But you might consider having different ingress controllers per team, API, security requirements, or just a single one at the cluster level if that is suitable based on your requirements.  

Additionally, please let's take into acocunt we already have another Reference Implementation that uses AGIC + that might be rebased in the future on top of the very same baseline. 

Please stay tuned.
 
/cc @doodlemania2
