### ISSUE TITLE
Azure Policy prevents Traefik Ingress Controller Installation 

### ISSUE THREAD

**Issue by kendallroden** [mspnp/aks-secure-baseline#250]
When you attempt to install the Traefik Ingress Controller using the instructions in "08-secret-management-and-ingress-controller.md", the Traefik pods will never come up. After digging, I realized it is because the Traefik deployment is trying to use privilege escalation, which is blocked by Azure Policy. Maybe I am missing something but here is the output:
![Screen Shot 2021-10-28 at 3 12 29 PM](https://user-images.githubusercontent.com/22015135/139328528-b8c40f13-0dde-463f-a725-48d4e704ae4a.png)

**Comment by ckittel** [comment]
Thanks @kendallroden for the suggestion of adding `allowPrivilegeEscalation: false` to help avoid policy-related blocks.  @magrande confirmed upstream that it's a supported configuration, without adding any additional capacities (since this implementation doesn't open any privileged ports).  He added it as part of #252 

Going to close out the issue, but I did see your other ACR notice, where you offered a PR for that -- so we can track that via the PR if you happen to get a chance to open it.

Cheers!
