### ISSUE TITLE
Unable to fetch object ID

### ISSUE THREAD

**Issue by rambabu0063** [mspnp/aks-secure-baseline#27]
Hi Team,

I was trying to add user in to Azure key vault access policy but I am  facing issue .
I am following the below link:  https://github.com/mspnp/aks-secure-baseline/blob/main/07-workload-prerequisites.md

My user format is username@customerdomainname
<img width="619" alt="unable-to-get-objectid" src="https://user-images.githubusercontent.com/57993345/89171542-f75f7a00-d59e-11ea-9067-e1a8cd91342b.PNG">

could you please look into this issue.

**Comment by nitinkhandelwal26** [comment]
Yes, I am able to deploy only when I am using: username@customername.onmicrosoft.com only not with username@customername.tld

**Comment by ferantivero** [comment]
thanks for sharing this @rambabu0063, please let us close this issue as it seems to be a problem trying to add more users or differently than prescribed in this Reference Implementation. 

But please be sure you're specifying a valid user principal. For more information, please take a look at https://docs.microsoft.com/en-us/azure/key-vault/general/secure-your-key-vault#data-plane-and-access-policies.

**Comment by nitinkhandelwal26** [comment]
@ferantivero thanks for reply but this username@customername.tld has global admin access and owner on subscription.

Seems this is an issue, please invite a user to your AAD and make him global admin and owner to subscription, then try to deploy this implementation with that user. Then you will see that error.
@ckittel Please verify this scenario.

**Comment by ckittel** [comment]
@nitinkhandelwal26, as @ferantivero said, we likely won't change the reference implementation to account for this situation; however, I am curious as to the use case you're solving in this step of the process.  This prereq step is not really part of any specific workflow here; meaning the steps are just a "means to an end" where the "means" are not the part being taught, but instead of end result of this specific certificate being eventually sourced from Key Vault for Traefik.  We actually added a step to remove the permissions termporarly granted to help make this even more clear.  Ideally this would be done via ARM templates, but "certificates" are not a [resource that are ARM managed](https://docs.microsoft.com/azure/templates/microsoft.keyvault/vaults) for KeyVault.  Most oranizations already have an established process for raw "certificates" in their Key Vault, which very from org to org, and we are only "simulating" by just doing the import.

So, while Key Valut certificate management isn't the focus of this reference implementation, I'd love to still learn a bit more about this scenario your are embarking on with the prividledge guest in your AAD.  Can you explain it a little more?  If you don't have time, that's fine and we can (re-)close this issue ... since it's purely accademic anyway at this point.

**Comment by nitinkhandelwal26** [comment]
Thanks a lot @ckittel for your response, the scenario is:

1) we have created an account with let's say abc@qrt.xyz 
2) added this account to our subscription as a global administrator, 
3) provided OWNER role to this account in our subscription IAM, (also added a co-admin)
4) now deploy this reference implementation using this account, then this we faced.

I have created this subscription then tried it with my account, then used @rambabu0063 account, then one other colleague account, but none was working,
Then created an account within AAD like abc@ourtenent.onmicrosoft.com
this was working and used for deployment.
This should not be the case in real scenario as when we get a subscription from our organization then we have our invite our organization users to that subscription, and use those organization users for deployment only. like ckittel@microsoft.com should be added to subscription and used for deployment, not ckittel@microsoft.onmicrosoft.com.

**Comment by ckittel** [comment]
Thanks for the added context @nitinkhandelwal26. Yeah an AAD "Guest" user is limited in what they can perform.  KeyVault in paticular used to restrict access to data plane interactions to only "Member" users.  Sounds like that restriction is still in place.  You can convert a "Guest" account in AAD to a "Member" using [`Set-AzureADUser`](https://docs.microsoft.com/powershell/module/azuread/set-azureaduser) `-UserType member`  (I'm not aware of the sytax for `az ad` -- if there even is one for this)

We have a support article on this: <https://support.microsoft.com/en-us/help/3192496/external-co-administrator-accounts-receive-warnings-and-errors-when-th>  Not sure how up to date it is, but speaks to this topology.

**Comment by nitinkhandelwal26** [comment]
Thanks a lot @ckittel, will try and get back to you if we still face any error.

**Comment by ckittel** [comment]
I'm going to go ahead and close the issue since there will be no changes on the reference implementation here to handle this scenario.  You're welcome to continue to comment on it though if desired, and any new issues you can open a new issue for.  Cheers.
