### ISSUE TITLE
Cluster-contained state (PVC, etc)

### ISSUE THREAD

**Issue by nitinkhandelwal26** [mspnp/aks-secure-baseline#41]
Hello Team,

Any plan to provide reference implementation on statefulset?

Regards,

**Comment by ckittel** [comment]
We sure do, @nitinkhandelwal26.  Since we don't encourage state in your cluster (as a general rule), it doesn't make sense to add that as part of the baseline.  Handling state impacts your your [Architecture Pillars](https://docs.microsoft.com/azure/architecture/framework/), so we want to do dedicated content for that. 

That reference architecture and implementation will be directly based off of this baseline.  Think of "fork + modifications" to the point that you could "diff the two repos" to see what was changed.  We don't have a timeline for that material, but it's on the short list that we plan to move to next!  If you have anything you'd like to recommend we covered specifically, feel free to add it here to this thread.  We'll likely close this issue here, since this won't be implemented in this repo and was just a question anyhow :)

**Comment by nitinkhandelwal26** [comment]
Thank you very much @ckittel for your response. an IoT common scenario is a connected vehicle application wherein fleet management service, we need to keep the state of the vehicle and receive telemetry data.

This is the most sought scenario in today's IoT world where the connected vehicle is sending telemetry data continuously or another scenario where you have a gas refinery where the gas detector is used to detect the gas leakage.

I have searched almost all guidance provided by Microsoft but stateful set implementation is cannot find anywhere also there is no material available as well. (only this is available https://docs.microsoft.com/en-us/azure/aks/concepts-clusters-workloads )
It would be really helpful if you can provide this type of StatefulSets implementation in this type of architecture.
