### ISSUE TITLE
What is XMAS scale out and upgrade Node values in Subnet details table

### ISSUE THREAD

**Issue by nitinkhandelwal26** [mspnp/aks-secure-baseline#58]
Hello Team,
Can you please specify what is XMAS Scale-out and Upgrade Node values in the subnet details table mentioned in 
https://github.com/mspnp/aks-secure-baseline/blob/main/networking/topology.md

Regards,
Nitin

**Comment by ferantivero** [comment]
thanks for this inquiry @nitinkhandelwal26 that column express just an initial percentage estimation of how much the cluster is going be scaled out (extra agent nodes basically). Please note that number itself is not based on any actual data as it was just for sake of exercising the planning for the right sizing the cluster's subnet. 

The main idea is to plan ahead for more than you are estimating to grow in the future so the subnet does not get quickly exhausted as long as you scale out the cluster.

Regarding the name of that column is something we could revisit to be more self explained. 

Please feel free to close this issue if you consider the question has been answer.

**Comment by nitinkhandelwal26** [comment]
Thank you for your response @ferantivero.
is Christmas uses surge taken into account in XMAS scale out column?
what is upgrade node value 1?

**Comment by ferantivero** [comment]
@nitinkhandelwal26 yes, fictitiously speaking that season has been taken into account. But this is a more general purpose column for the max scale out we're expecting. 

Please take into account that this is just an initial reference table and possibly you might want to add as many column as you need for your own implementation in order to right size your subnet(s).

Regarding the upgrade node value 1, while upgrading the your AKS cluster a new agent node is spawned to move things around. But please let us share the docs you could refer for further information: [Configure Azure CNI networking in Azure Kubernetes Service (AKS)](https://docs.microsoft.com/en-us/azure/aks/configure-azure-cni)

**Comment by nitinkhandelwal26** [comment]
Thank you @ferantivero for explanation.
