### ISSUE TITLE
CSI Driver provider for Keyvault  for TLS Cert

### ISSUE THREAD

**Issue by mozts2005** [mspnp/aks-secure-baseline#73]
https://github.com/mspnp/aks-secure-baseline/blob/main/inner-loop-scripts/shell/1-cluster-stamp.sh#L126-L148
https://github.com/mspnp/aks-secure-baseline/blob/main/workload/traefik.yaml#L281-L286

Why would I want to mount my TLS cert that is only used by my ingress?

Would it not be better to use http://akv2k8s.io to sync the TLS cert to K8s?

**Comment by ckittel** [comment]
Thank you for the question @mozts2005 . To my knowledge, the OSS akv2k8s wasn't evaluated as part of this implementation. The dependency on the Azure Key Vault Secret Store CSI Driver Provider also came with some notable risk (customer's typically don't like shipping product versioned "0.0.8" into their production clusters).  From a customer support perspective, we gathered from our interviews that customers would receive more proative support with the CSI Driver than any other solution that was evaluated -- considering the origin of that code and the longer term plan with this CSI driver provider.  Thesecrets store CSI driver provider aligned with the requirements of showing pod managed identity to retrieve a secret from KeyVault, and shows how you might need to bring external componets to your cluster to stasify business requirements.

Obviously all customers have all options available to them.  The moment you take a dependency on one, someone else asks, why didn't you use the other.  And those are all fair questions (and frankly very expected).  This work was to start conversations exactly like this.  Encouraing all to align business requirements, product roadmap, supportability and prioritization of traits (open source, 1st party, etc) to the solution.

I'll add Sparebanken Vest's OSS work here to our radar to evaluate further.  Thanks!

**Comment by mozts2005** [comment]
my point is that using Azure Key Vault Secret Store CSI Driver Provider violates most corporate policies about encryption at rest. As the mount in the Pod will not be encrypted.

**Comment by ckittel** [comment]
Indeed, having CSI pull the identified keys into the local pod mount will no doubt violate some corporate policies - as we expect other parts of this "start your conversation here" baseline to do (private API server, for example).  For others, this will be suitable (as might any other solution they bring).  It would probably be a good idea to make this topic clear to our readers if they assume otherwise.  We are currently planning some tweaks to the main document, and I'll slot in some content around that.  Might be a couple weeks out yet.  Thanks.

**Comment by ckittel** [comment]
Indeed, having CSI pull the identified keys into the local pod mount will no doubt violate some corporate policies - as we expect other parts of this "start your conversation here" baseline to do (private API server, for example).  For others, this will be suitable (as might any other solution they bring).  It would probably be a good idea to make this topic clear to our readers if they assume otherwise.  We are currently planning some tweaks to the main document, and I'll slot in some content around that.  Might be a couple weeks out yet.  Thanks.

However, to be clear about the technical implementation of this provider, I think it _might_ be "less bad" than many organizations might think.  Is this secret being mounted in a Pod?  Yup.  However it's mounted on a RAM disk and is completely ephemeral.  Combined that with the built-in isolation where pods can't access content from other pod mounts, you're secure there.

The major attack vector is still the node.  If $BadUser gains access to the node, they can already exec into docker containers and read ENV and mounts anyhow.

**Comment by mozts2005** [comment]
@ckittel I agree with you. I just have worked with two clients that wont use Azure Key Vault Secret Store CSI Driver Provider for the above issue.

**Comment by ckittel** [comment]
Yeah, I can feel the apprehension from some.  Hopefully once they know how it works, the attack vectors appear similar to other solutions (ephemeral, but scoped to pod instead of within a running process).  Of course, having your application source secrets themselves where possible is another avenue (App Configuration + KV, etc), completely bypassing any of this conversation.  Of course, that's not possible for code you don't own.

**Comment by ckittel** [comment]
This is a great conversation, I'm going to leave it open for a few more days in case others wish to chime in or just see this level of conversation.  We'll likely close those longer term here as we try to clarify in the long-form article on docs.microsoft.com in our next update cycle on this.

**Comment by ferantivero** [comment]
I'd like share some thoughts on top of this conversation to be revisited while discussing this in the future:

1. most of what've been discussed in this awesome thread could be more associated to the upstream [CSI Driver](https://kubernetes-csi.github.io/docs/csi-driver-object.html) as I see it, since this is the one in charge of mounting [an ephemeral local volume](https://kubernetes-csi.github.io/docs/ephemeral-local-volumes.html) containing the secrets rather than the registered provider to fetch them (Azure Key Vault Secret Store CSI Driver Provider or any other). That said, definitely data encryption at rest must gravitate this sort of discussions, but under this very specific configuration I'm personally having a hard time trying to determine whether it'd be a requirement. Although I clearly see this becoming a consideration:
   - when the volume has an independent lifecycle to an individual pod, it means provided it gets configured as `Persistent`
   - when a user gains access
1. using k8s native `secrets` for this would replicate what is already stored in the platform-managed secret store of preference (e.g. Azure Key Vault) into `etcd`.
1. sync certs into k8s native `secrets` enables the possiblity to reference them as `TLS secrets` using `ingress objects`, and in that case it wouldn't necessarily require ENVs at the pod level. This could be the case when using `Cert-Manager` with Let's Encrypt or any other similar solutions.
