### ISSUE TITLE
Azure API Management in between Azure App Gateway and ingress controller

### ISSUE THREAD

**Issue by nitinkhandelwal26** [mspnp/aks-secure-baseline#81]
Hello Team,

If our cost model is to charge the customer based on API incoming requests or the number of hits then would it be wise to include API management between App Gateway and Ingress controller? or any other components that can be used for this purpose? Request you to please provide Guidance or Suggestions on this.

Regards,

**Comment by ckittel** [comment]
Personally, I'd only consider using [API Management in the billing solution](https://azure.microsoft.com/en-us/blog/how-to-monetize-apis-with-azure-api-management/) if I was using it for _more than_ the built in telemetry for billing purposes.  API Management has a lot of features you might find helpful in various situations, but it's more cost effective if you're using a _multitude of them_ (for example, rate limiting, AAD AuthN, etc).  API Management, especially a VNet-homed instance (as you'd want between AAG and AKS) can be seen as relatively expensive -- so you'd want to make sure you're optimizing your cost where it matters most to your business.  API Management doesn't really offer any sort of "built in" metered billing model, only the telemetry you pull from the service, broken down by your products/customers. Ultimately you'd still need to write a daily/monthly/etc billing job that pulls the usage telemetry out and into your billing process.

To that end, you might be just fine using the telemetry coming out of your ingress controller - as long as all the data you need can be logged from within Traefik (or whatever ingress controller you are running) and it's authoritative.  However, with anything dealing with charging a customer, you'll want to make sure that you're building a system around this that YOU and YOUR CUSTOMER trusts. Reliable, transparent, fraud resistant (CustomerA shouldn't be able to CustomerB's bill) auditable - charging for healthy requests (subset of 2xx, 3xx, 4xx), not server failures (5xx), etc. As with anything you deem important to your business, it might be best to be very intentional about the logging of billing charges, and bring it back into middleware in your code -- that way you know for sure you're logging only the parts that matter.  However, lifting it up to ingress telemetry (ingress controller, some other middleware layer you add like API Management), would be a great cross-cutting concern, leaving your code to perform just the code's responsibilities.

Due to the fraud component, I'm assuming you're going to be needing to bill AFTER you have AuthN/AuthZ'd the request, so it might come down to where/how you plan on doing that -- so if it's APIM you use, or Traefik, just make sure you're grabbing billing points for only those "healthy/auth'd" requests.

**Comment by nitinkhandelwal26** [comment]
@ckittel Thank you very much for the guidance...It is really helpful in giving a fraud component perspective...
