### ISSUE TITLE
AKS cluster not visible while logging using  AD user bu0001a0008-admin

### ISSUE THREAD

**Issue by rambabu0063** [mspnp/aks-secure-baseline#90]
Hi Team,

I have deployed the full solution in my environment but I am not able to see the cluster if I login using  AD user  as **bu0001a0008-admin**  .

could you please suggest how can i get access or any additional configuration needs to be done.

after add IAM role manually , i am able to access the cluster.

**Comment by ckittel** [comment]
Hey there @rambabu0063 -- can you say more about your situation?  "not able to see the cluster if I login using AD user ..."  login to what specifically?  Azure Portal? az cli? kubectl?

If you're talking about az cli or Azure Portal, that is correct behavior you are seeing.  That break-glass admin user is for cluster access (kubectl, etc) only, no where did we assign it Azure RBAC permissions to interact with the Azure Resources.  It's an in-cluster admin, not an Azure RBAC user that can use the portal to interact with other resources.  Now of course, you can grant that user said additional permissions if you feel that is appropriate - but consider your separation/scope of duties carefully when doing that.

**Comment by nitinkhandelwal26** [comment]
Correct @ckittel but now since 1.18.8 version of AKS kubernetes dashboard is disabled and and from 1.19 version it will not be managed. So, to see namespace, pods and other cluster related information we need to login to azure portal only.

I am not talking about other resources in subscription or cluster configuration properties access to this break glass user but cluster related stuff like namespace, pods, workloads, service and ingress section of azure portal 
![20201003_002335](https://user-images.githubusercontent.com/10863548/94959422-c81da880-050e-11eb-8b79-7b39b5f6cf89.jpg)
menus should be accessible to this break glass user in aks cluster.

Please provide your view..

**Comment by ckittel** [comment]
If you want to provide access with that user, then you'd need to grant that user (or the group it's a member of) Azure RBAC permissions in azure.  I don't propose that you use that specific user for that - instead I would urge you to reserve that for an in-cluster admin only - separating the blast radius of a compromised user in that group.  But, as I mentioned, you're welcome to grant any user or group whatever Azure RBAC permissions you want, including the ability to see this scraped data from the cluster in the Azure portal.

In a month or so, we'll be updating this RI to include the new [Azure RBAC-based mapping to k8s RBAC group management](https://docs.microsoft.com/en-us/azure/aks/manage-azure-rbac) as that feature roles closer to production.  You might find the overlap between that feature and your desires to be closer.

**Comment by nitinkhandelwal26** [comment]
Hello @ckittel,
Thanks for your reply.
I just discovered one more thing:

I have created Azure AD Group with End user given in inner loop script, then associate this user to view group in cluster rbac:

File : https://github.com/mspnp/aks-secure-baseline/blob/main/cluster-baseline-settings/user-facing-cluster-role-aad-group.yaml
Code:
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: contosobicycle-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - kind: Group
    name: replaced-it-with-my-ad-group-id

after that when i logged in with this user then i was able to create namespace and deploy memcached pod into it.

Want  to understand is it correct behaviour or i am missing something, as i have added this group to "view" cluster binding only.

![image (2)](https://user-images.githubusercontent.com/10863548/95612187-995c8080-0a80-11eb-8c96-a2b2b2e74d9e.png)

**Comment by ckittel** [comment]
Can you validate that `kubectl config view` returns an `auth-provider` with the name `azure` and the `access-token` is one with a `unique-name` claim that matches the user in the "view" AD Group that you created?  Ensure that user is also the user of the `current-context`.

Let me know if you've validated those things, and then if so, we can schedule some time to look at the `view` role binding next.

**Comment by nitinkhandelwal26** [comment]
![image (3)](https://user-images.githubusercontent.com/10863548/96420163-c04e4b80-1212-11eb-9b31-00a54d8879cf.png)

**Comment by nitinkhandelwal26** [comment]
I have created new user and added to "view" group, then got above output..

**Comment by ckittel** [comment]
Gotcha, now I see where you're going with this. Your observation is correct, in order to use `az aks get-credentials` you need Azure RBAC permissions to do so. Specifically in your case that "view only" user will need the **Azure Kubernetes Service Cluster User Role** on your cluster resource. This allows the current user (your limited "view" user), the permission to invoke the "list cluster user credentials" API, which gets back the information necessary to populate your _kubeconfig_ file automatically.

You could instead attempt to populate your config file using `kubectl config set-credentials` directly using information you've gathered from another successful `az aks get-credentials` call.  That way you can document that process without needing to grant specific Azure RBAC access for that internal account.

All that said, we are soon going to be recommending that users instead be given Azure RBAC permssions anyway to manage their relationship with the cluster, using the new Azure RBAC integration feature that is in preview.  In this way, users are assigned scoped Azure RBAC "view" permissions on cluster resources, and the configuration of that within the cluster itself is handled for you (no need to manage that permission list in yaml resources).  The point of me saying this is that soon, a user like this will be expected to have Azure RBAC permissions anyhow.  You're still welcome to not go down that path, this choice will always be yours.  But for more "out of the box success" we'll be headed toward Azure RBAC-managed access.

**Comment by rambabu0063** [comment]
Hi Team,
I was just trying to use kubectl config set-credentials , but cluster name and server name is not getting added.
could you please suggest ,how to proceed further.
<img width="492" alt="set-credential" src="https://user-images.githubusercontent.com/57993345/96579565-af760680-12f4-11eb-8c6e-15a76856247a.PNG">
<img width="535" alt="config-view" src="https://user-images.githubusercontent.com/57993345/96579600-ba309b80-12f4-11eb-85f4-3af97ecdef06.PNG">

**Comment by nitinkhandelwal26** [comment]
Should we provide these Azure RBAC roles to these K8s groups? or any other option.. we have tried maximum options to add cluster and context, but its not working...

**Comment by ckittel** [comment]
Correct, for `kubectl` in addition to `kubectl set-credentials` you also need to make sure the cluster is added via `kubectl set-cluster` after which you can call `kubectl use-context`.  That's why I suggested you model it off of a successful `az aks get-credentials` call so you know what values to set for the cluster.

This step is not AKS specific, just base kubernetes.

I'll see if I can get some time today to record the steps for you.

**Comment by nitinkhandelwal26** [comment]
Thank you so much @ckittel , i will try this cluster set-context and use-context and update you..

**Comment by ckittel** [comment]
I just did a test, and I had no problems with anything working out of the box wrt "view" readers.  Here was my process, see if you can identify where your step is different.

1. `az login` as someone that has Azure RBAC permissions to do the deployment
1. Deployed Network as per instructions
1. Deployed Cluster - with AAD Admin Group Set to Tenant X and Default Admin Group Set to Group X
1. With the same user as above I ran `az aks get-credentials -g rg-bu0001a0008 -n $AKS_CLUSTER_NAME` (as per the instructions) -- this stubs out an "empty" `kubectl` config file with all the connection information necessary (but no user information yet)
1. Then I called `kubectl get nodes` -- which kicked off a device auth session, in which I provided the username and password for one of the cluster admins in `Group X` (this user has zero Azure RBAC permissions)
1. As that kubernetes admin, I enrolled the cluster in GitOps such that it picks up the `user-facing-cluster-role-aad-groups.yaml` configuration which has a section that looks like.
    ```yaml
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: contosobicycle-view
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: view
    subjects:
      - kind: Group
        name: <my "view" AAD group guid is here>
    ```
1. I then re-executed `az aks get-credentials -g rg-bu0001a0008 -n $AKS_CLUSTER_NAME` to simply clobber my local config (there is probably a more elegant way to do this :)).
1. Then I called `kubectl get nodes` -- which kicked off a device auth session again (since it lost user information in the prior steo), in which I provided the username and password for one of the cluster viewer users in the group identified above in the role binding (this user has zero Azure RBAC permissions)
1. this resulted in a bad permission response (and rightfully so, a viewer doesn't have GET permission on _nodes_)
1. I then did `kubectl get pods -A` which did show me all pods running (permssion that a view user has by default)
1. I also ran a `kubectl auth can-i --list` which showed me all the `get`/`list`/`watch` this reader account uses.

If I wouldn't have used `az aks get-credentials` then I would have needed to set up my kubectl contexts via the kubernetes documentation on the such -- but I wouldn't recommend trying to go down this path.  It would be better to let `az ask get-credentials` do the work for you (you just need to do it as the same user that deployed the cluster -- not as any other user).  That will simply stub out the config file for you.  Who you identify as with your first `kubectl` command is up to you!

**Comment by nitinkhandelwal26** [comment]
Thank you @ckittel I tried below steps after applying user facing rbac yaml on same or a new linux vm:
1) Use get-credential with admin user
2) then login with this new view user 
I was able to create namespace using with view user and when I saw config view then I could see the cluster admin permission with this user as well..it means previous context of admin user was merged with this newly added view user...

**Comment by ckittel** [comment]
I'd check your group memebership for that auth'd user.  `kubectl auth can-i --list` will show you all permissions the current auth'd `kubectl` user can have.  If you are seeing more permissions than expected, then validate the who you are signed in as, AAD group membership, and what k8s roles that group is assigned to.  Following the instructions in this repo, a user that is exclusively assigned to the `view` ClusterRole cannot create namespaces -- just tested this to double check.

**Comment by ckittel** [comment]
You know you don't have any overlaps in permission configuration when your output looks similar to this.

```bash
kubectl auth can-i --list
```

```output
Resources                                       Non-Resource URLs   Resource Names   Verbs
selfsubjectaccessreviews.authorization.k8s.io   []                  []               [create]
selfsubjectrulesreviews.authorization.k8s.io    []                  []               [create]       
bindings                                        []                  []               [get list watch]
configmaps                                      []                  []               [get list watch]
endpoints                                       []                  []               [get list watch]
events                                          []                  []               [get list watch]
limitranges                                     []                  []               [get list watch]
namespaces/status                               []                  []               [get list watch]
namespaces                                      []                  []               [get list watch]
persistentvolumeclaims/status                   []                  []               [get list watch]
persistentvolumeclaims                          []                  []               [get list watch]
pods/log                                        []                  []               [get list watch]
pods/status                                     []                  []               [get list watch]
pods                                            []                  []               [get list watch]
replicationcontrollers/scale                    []                  []               [get list watch]
replicationcontrollers/status                   []                  []               [get list watch]
replicationcontrollers                          []                  []               [get list watch]
resourcequotas/status                           []                  []               [get list watch]
resourcequotas                                  []                  []               [get list watch]
serviceaccounts                                 []                  []               [get list watch]
services/status                                 []                  []               [get list watch]
services                                        []                  []               [get list watch]
controllerrevisions.apps                        []                  []               [get list watch]
daemonsets.apps/status                          []                  []               [get list watch]
daemonsets.apps                                 []                  []               [get list watch]
deployments.apps/scale                          []                  []               [get list watch]
deployments.apps/status                         []                  []               [get list watch]
deployments.apps                                []                  []               [get list watch]
replicasets.apps/scale                          []                  []               [get list watch]
replicasets.apps/status                         []                  []               [get list watch]
replicasets.apps                                []                  []               [get list watch]
statefulsets.apps/scale                         []                  []               [get list watch]
statefulsets.apps/status                        []                  []               [get list watch]
statefulsets.apps                               []                  []               [get list watch]
horizontalpodautoscalers.autoscaling/status     []                  []               [get list watch]
horizontalpodautoscalers.autoscaling            []                  []               [get list watch]
cronjobs.batch/status                           []                  []               [get list watch]
cronjobs.batch                                  []                  []               [get list watch]
jobs.batch/status                               []                  []               [get list watch]
jobs.batch                                      []                  []               [get list watch]
daemonsets.extensions/status                    []                  []               [get list watch]
daemonsets.extensions                           []                  []               [get list watch]
deployments.extensions/scale                    []                  []               [get list watch]
deployments.extensions/status                   []                  []               [get list watch]
deployments.extensions                          []                  []               [get list watch]
ingresses.extensions/status                     []                  []               [get list watch]
ingresses.extensions                            []                  []               [get list watch]
networkpolicies.extensions                      []                  []               [get list watch]
replicasets.extensions/scale                    []                  []               [get list watch]
replicasets.extensions/status                   []                  []               [get list watch]
replicasets.extensions                          []                  []               [get list watch]
replicationcontrollers.extensions/scale         []                  []               [get list watch]
ingresses.networking.k8s.io/status              []                  []               [get list watch]
ingresses.networking.k8s.io                     []                  []               [get list watch]
networkpolicies.networking.k8s.io               []                  []               [get list watch]
poddisruptionbudgets.policy/status              []                  []               [get list watch]
poddisruptionbudgets.policy                     []                  []               [get list watch]
                                                [/api/*]            []               [get]
                                                [/api]              []               [get]
                                                [/apis/*]           []               [get]
                                                [/apis]             []               [get]
                                                [/healthz]          []               [get]
                                                [/healthz]          []               [get]
                                                [/livez]            []               [get]
                                                [/livez]            []               [get]
                                                [/openapi/*]        []               [get]
                                                [/openapi]          []               [get]
                                                [/readyz]           []               [get]
                                                [/readyz]           []               [get]
                                                [/version/]         []               [get]
                                                [/version/]         []               [get]
                                                [/version]          []               [get]
                                                [/version]          []               [get]
```

**Comment by rambabu0063** [comment]
thank you @ckittel 

I have followed the steps provided by you to check view role.  Now I am not able to view pods and namespaces.
when I executed  kubectl auth can-i --list  I got very less number of resources.

<img width="595" alt="kubectl-auth" src="https://user-images.githubusercontent.com/57993345/96691071-16052e00-13a2-11eb-9132-e4a4827d1f85.PNG">
<img width="945" alt="kubectl-get-pods" src="https://user-images.githubusercontent.com/57993345/96691085-1998b500-13a2-11eb-9088-5b7bc521bee2.PNG">

could you please help us to get all resources those are available for view user by default.

**Comment by ckittel** [comment]
That's the exact expected output of a user that is assigned to no groups in any roles. Did you forget to deploy your ClusterRoleBindings and/or did you log in with a user not assigned to your viewer group? Double check your role bindings exist in the cluster and they have the expected values. And double check that the user you auth'd with was the right user.

**Comment by ckittel** [comment]
Here is a checklist for you that will hopefully help you

- [ ] I have set up (at least) two Azure AD groups, one for admins and one for viewers.
- [ ] I added at least one distinct user to each group.
- [ ] I have completed the infrastructure deployment, with the tenant ID set to the tenant of the first step.
- [ ] As the same `az login` context user in the prior step, I have executed the `az aks get-credentials` for that cluster.
- [ ] I have set up my `user-facing-cluster-role-aad-group.yaml` file (or similar) with group object IDs set up in the first step.
- [ ] I have applied `user-facing-cluster-role-aad-group.yaml` file (or similar) via Flux integration (or manually) to the cluster and verified the `ClusterRoleBindings` exist after that.  This step forced me to log in via the device flow and I identified as a user in the "for admins" group from the first step.
- [ ] I have either added a new user context to my kubeconfig (and switched to that context) or simply re-executed `az aks get-credentials` (As the same `az login` context user from the third step) for the cluster to wipe out my local settings
- [ ] I have executed `kubectl auth can-i --list`. This step forced me to log in via the device flow and I identified as a user in the "for viewers" group from the first step.

**Comment by nitinkhandelwal26** [comment]
We little bit modified the inner loop script:
------------------------------------------------------------------------------------------------------------
#Creating AAD groups which will be associated to k8s out of the box cluster roles
k8sClusterAdminAadGroupName="k8s-cluster-admin-clusterrole-${AKS_CLUSTER_NAME}"
k8sClusterAdminAadGroup=$(az ad group create --display-name ${k8sClusterAdminAadGroupName} --mail-nickname ${k8sClusterAdminAadGroupName} --query objectId -o tsv)
k8sAdminAadGroupName="k8s-admin-clusterrole-${AKS_CLUSTER_NAME}"
k8sAdminAadGroup=$(az ad group create --display-name ${k8sAdminAadGroupName} --mail-nickname ${k8sAdminAadGroupName} --query objectId -o tsv)
k8sEditAadGroupName="k8s-edit-clusterrole-${AKS_CLUSTER_NAME}"
k8sEditAadGroup=$(az ad group create --display-name ${k8sEditAadGroupName} --mail-nickname ${k8sEditAadGroupName} --query objectId -o tsv)
k8sViewAadGroupName="k8s-view-clusterrole-${AKS_CLUSTER_NAME}"
k8sViewAadGroup=$(az ad group create --display-name ${k8sViewAadGroupName} --mail-nickname ${k8sViewAadGroupName} --query objectId -o tsv)

#EXAMPLE of an User in View Group

{ #'try' block
    AKS_END_USER_OBJECTID=$(az ad user show --id $AKS_ENDUSER_NAME --query objectId -o tsv)
} || { #'catch' block
    echo "User does not exists"
}
if [ -z "$AKS_END_USER_OBJECTID" ] 
then
    echo "creating end user"
    export AKS_END_USER_OBJECTID=$(az ad user create --display-name $AKS_ENDUSER_NAME --user-principal-name $AKS_ENDUSER_NAME --force-change-password-next-login  --password $AKS_ENDUSER_PASSWORD --query objectId -o tsv)
fi

{ #'try' block
    K8S_RBAC_AAD_PROFILE_END_USER_GROUP_AND_USER_ASSOCIATION_CHECK=$(az ad group member check --group $k8sViewAadGroupName --member-id $AKS_END_USER_OBJECTID --query value -o tsv)
} || { #'catch' block
        echo "user does not exists in view group"
}

if [ $K8S_RBAC_AAD_PROFILE_END_USER_GROUP_AND_USER_ASSOCIATION_CHECK = "false" ]; 
then
    echo "adding member to group" 
    az ad group member add --group $k8sViewAadGroupName --member-id $AKS_END_USER_OBJECTID
fi

echo "starting baseline cluster configuration"

user_facing_cluster_role_aad_group=$(pwd)/_daf-ct-dta-infra-container/cluster-baseline-settings/user-facing-cluster-role-aad-group.yaml

if grep -q metadata "$user_facing_cluster_role_aad_group"; then
echo $user_facing_cluster_role_aad_group
cat $user_facing_cluster_role_aad_group | \
     sed "s#<replace-with-an-aad-group-object-id-for-this-cluster-role-binding-cluster-admin>#$k8sClusterAdminAadGroup#g" | \
     sed "s#<replace-with-an-aad-group-object-id-for-this-cluster-role-binding-admin>#$k8sAdminAadGroup#g" | \
     sed "s#<replace-with-an-aad-group-object-id-for-this-cluster-role-binding-view>#$k8sViewAadGroup#g" | \
     sed "s#<replace-with-an-aad-group-object-id-for-this-cluster-role-binding-edit>#$k8sEditAadGroup#g" \
     > $user_facing_cluster_role_aad_group

cat $user_facing_cluster_role_aad_group
kubectl apply -f $user_facing_cluster_role_aad_group
else
echo "file content does not exist, kindly re-download file $user_facing_cluster_role_aad_group and re-apply"
fi

--------------------------------------------------------------------------------------------------------------------------------------------
in above code before applying "user-facing-cluster-role-aad-group.yaml" we were able to see all user ids were assigned to placeholders.

After that we logged in using admin user then did get cendentail,
Then we logged in using this above created end user then that was the output.

**Comment by ckittel** [comment]
I'm a little confused by your `... | cat $file | sed "s##$k8sViewAadGroup#g | ..." command there. are placeholders supposed to be replaced in there `sed "s#MY_READ_GROUP#$k8sViewAadGroup#g` or something?  Maybe that `sed` command is working right, but just not seeing how (my `sed`-foo is a little weak :).

However, you said that when you do your final `cat` then things are looking good, so not sure my prior statement matters.

After you execute `kubectl apply -f $user_facing_cluster_role_aad_group` -- I assume that was successful?  How did you verify that it was successful? (this was my sixth checkbox above).

When I real "we added few users to the "view" user group, but still a similar output..." really speaks to me that the group is either 1) in a different tenant than what the cluster is expecting the group to be in 2) the ClusterRoleBinding is malformed in a way that it's not actually applying what you think it is 3) the ClusterRoleBinding is not actually being applied or 4) you're somehow identifying yourself as the wrong user (unlikely, but wanted to list it)

**Comment by nitinkhandelwal26** [comment]
Below output I have verified with Admin user:

testadm@dafct-dev2-dta-cdp-testviewrole-vm:~$ az aks get-credentials -n aks-geo7                                                                                        gzvofvyu6 -g daf-lan1-d-euwe-rsg-k8s_testcluster001 --admin
Merged "aks-geo7gzvofvyu6-admin" as current context in /home/atosadm/.kube/confi                                                                                        g
testadm@dafct-dev2-dta-cdp-testviewrole-vm:~$ kubectl get clusterroles                                                                                                  NAME                                                                   CREATED A                                                                                        T
aad-pod-identity-mic                                                   2020-10-1                                                                                        9T13:28:34Z
aad-pod-identity-nmi                                                   2020-10-1                                                                                        9T13:28:39Z
**admin**                                                                  2020-10-1                                                                                        9T13:24:18Z
aks-service                                                            2020-10-1                                                                                        9T13:24:30Z
azure-npm                                                              2020-10-1                                                                                        9T13:24:32Z
azure-policy-webhook-cluster-role                                      2020-10-1                                                                                        9T13:24:32Z
**cluster-admin**                                                          2020-10-1                                                                                        9T13:24:18Z
container-health-log-reader                                            2020-10-1                                                                                        9T13:24:32Z
**edit**                                                                   2020-10-1                                                                                        9T13:24:18Z
gatekeeper-manager-role                                                2020-10-1                                                                                        9T13:24:33Z
kured                                                                  2020-10-1                                                                                        9T13:29:10Z
omsagent-reader                                                        2020-10-1                                                                                        9T13:24:30Z
policy-agent                                                           2020-10-1                                                                                        9T13:24:32Z
secretproviderclasses-role                                             2020-10-1                                                                                        9T13:29:46Z
system:aggregate-to-admin                                              2020-10-1                                                                                        9T13:24:18Z
system:aggregate-to-edit                                               2020-10-1                                                                                        9T13:24:18Z
system:aggregate-to-view                                               2020-10-1                                                                                        9T13:24:18Z
system:auth-delegator                                                  2020-10-1                                                                                        9T13:24:18Z
system:azure-cloud-provider                                            2020-10-1                                                                                        9T13:24:32Z
system:azure-cloud-provider-secret-getter                              2020-10-1                                                                                        9T13:24:32Z
system:basic-user                                                      2020-10-1                                                                                        9T13:24:18Z
system:certificates.k8s.io:certificatesigningrequests:nodeclient       2020-10-1                                                                                        9T13:24:18Z
system:certificates.k8s.io:certificatesigningrequests:selfnodeclient   2020-10-1                                                                                        9T13:24:18Z
system:certificates.k8s.io:kube-apiserver-client-approver              2020-10-1                                                                                        9T13:24:18Z
system:certificates.k8s.io:kube-apiserver-client-kubelet-approver      2020-10-1                                                                                        9T13:24:18Z
system:certificates.k8s.io:kubelet-serving-approver                    2020-10-1                                                                                        9T13:24:18Z
system:certificates.k8s.io:legacy-unknown-approver                     2020-10-1                                                                                        9T13:24:18Z
system:controller:attachdetach-controller                              2020-10-1                                                                                        9T13:24:18Z
system:controller:certificate-controller                               2020-10-1                                                                                        9T13:24:18Z
system:controller:clusterrole-aggregation-controller                   2020-10-1                                                                                        9T13:24:18Z
system:controller:cronjob-controller                                   2020-10-1                                                                                        9T13:24:18Z
system:controller:daemon-set-controller                                2020-10-1                                                                                        9T13:24:18Z
system:controller:deployment-controller                                2020-10-1                                                                                        9T13:24:18Z
system:controller:disruption-controller                                2020-10-1                                                                                        9T13:24:18Z
system:controller:endpoint-controller                                  2020-10-1                                                                                        9T13:24:18Z
system:controller:endpointslice-controller                             2020-10-1                                                                                        9T13:24:18Z
system:controller:expand-controller                                    2020-10-1                                                                                        9T13:24:18Z
system:controller:generic-garbage-collector                            2020-10-1                                                                                        9T13:24:18Z
system:controller:horizontal-pod-autoscaler                            2020-10-1                                                                                        9T13:24:18Z
system:controller:job-controller                                       2020-10-1                                                                                        9T13:24:18Z
system:controller:namespace-controller                                 2020-10-1                                                                                        9T13:24:18Z
system:controller:node-controller                                      2020-10-1                                                                                        9T13:24:18Z
system:controller:persistent-volume-binder                             2020-10-1                                                                                        9T13:24:18Z
system:controller:pod-garbage-collector                                2020-10-1                                                                                        9T13:24:18Z
system:controller:pv-protection-controller                             2020-10-1                                                                                        9T13:24:18Z
system:controller:pvc-protection-controller                            2020-10-1                                                                                        9T13:24:18Z
system:controller:replicaset-controller                                2020-10-1                                                                                        9T13:24:18Z
system:controller:replication-controller                               2020-10-1                                                                                        9T13:24:18Z
system:controller:resourcequota-controller                             2020-10-1                                                                                        9T13:24:18Z
system:controller:route-controller                                     2020-10-1                                                                                        9T13:24:18Z
system:controller:service-account-controller                           2020-10-1                                                                                        9T13:24:18Z
system:controller:service-controller                                   2020-10-1                                                                                        9T13:24:18Z
system:controller:statefulset-controller                               2020-10-1                                                                                        9T13:24:18Z
system:controller:ttl-controller                                       2020-10-1                                                                                        9T13:24:18Z
system:coredns                                                         2020-10-1                                                                                        9T13:24:32Z
system:coredns-autoscaler                                              2020-10-1                                                                                        9T13:24:32Z
system:discovery                                                       2020-10-1                                                                                        9T13:24:18Z
system:heapster                                                        2020-10-1                                                                                        9T13:24:18Z
system:kube-aggregator                                                 2020-10-1                                                                                        9T13:24:18Z
system:kube-controller-manager                                         2020-10-1                                                                                        9T13:24:18Z
system:kube-dns                                                        2020-10-1                                                                                        9T13:24:18Z
system:kube-scheduler                                                  2020-10-1                                                                                        9T13:24:18Z
system:kubelet-api-admin                                               2020-10-1                                                                                        9T13:24:18Z
system:metrics-server                                                  2020-10-1                                                                                        9T13:24:30Z
system:node                                                            2020-10-1                                                                                        9T13:24:18Z
system:node-bootstrapper                                               2020-10-1                                                                                        9T13:24:18Z
system:node-problem-detector                                           2020-10-1                                                                                        9T13:24:18Z
system:node-proxier                                                    2020-10-1                                                                                        9T13:24:18Z
system:persistent-volume-provisioner                                   2020-10-1                                                                                        9T13:24:18Z
system:persistent-volume-secret-operator                               2020-10-1                                                                                        9T13:24:30Z
system:public-info-viewer                                              2020-10-1                                                                                        9T13:24:18Z
system:volume-scheduler                                                2020-10-1                                                                                        9T13:24:18Z
traefik-ingress-controller                                             2020-10-1                                                                                        9T13:30:44Z
**view**                                                                   2020-10-1                                                                                        9T13:24:18Z

I and Ram will retry the whole deployment again tomorrow morning India time and let you know the output of deployment along with the replaced output of Sed command for user_facing_cluster_role file... and also what comes after applying : kubectl apply..

Thank you so much @ckittel for your help, I am dragging this because want to understand where I am missing or wrongly implementing the stuff.

**Comment by ckittel** [comment]
Yeah, I'm all for you spending time to figure this out -- authorization shouldn't work without you knowing why -- because when it doesn't work, you need to know how to fix it :).  I'm sure we'll find the 💡 -moment for us here.

We want to be checking `ClusterRoleBindings`.  We know the `ClusterRoles` exist (they come out-of-the-box), it's the _bindings_ that are the most interesting.

**Comment by nitinkhandelwal26** [comment]
Thank you @ckittel for your guidance and support, you are correct, we need to know ClusterRoleBindings as that only defines the relationship between roles and group/user, I and Ram reapplied the cluster role binding manually after replacing the placeholders with object ids, and its working corrected as expected...
Sorry for troubling and Thank you so much again for helping us to figure out where the problem lies.. now the task for us to figure out why this sed command not working... @rambabu0063 will attach the successful output...

**Comment by rambabu0063** [comment]
thank you so much @ckittel  for your support.
please find the attached screenshot of successful test of view role.
<img width="944" alt="test-view-role-success" src="https://user-images.githubusercontent.com/57993345/96839097-56c67b00-1466-11eb-9383-35983f190dcc.PNG">

**Comment by ckittel** [comment]
You're welcome and and very glad to hear you were able to figure it out.

I'm going to go ahead and close this issue. Have a great weekend!

**Comment by nitinkhandelwal26** [comment]
Just one more comment: below is the output of a new deployment

020-10-22T10:44:32.4813132Z starting baseline cluster configuration
2020-10-22T10:44:32.4844330Z /home/vsts/work/r1/a/_daf-ct-dta-infra-container/cluster-baseline-settings/2-user-facing-cluster-role-aad-group.yaml
2020-10-22T10:44:32.4914511Z #  ------------------------------------------------------------
2020-10-22T10:44:32.4915862Z #   Copyright (c) Microsoft Corporation.  All rights reserved.
2020-10-22T10:44:32.4916953Z #   Licensed under the MIT License (MIT). See License.txt in the repo root for license information. 
2020-10-22T10:44:32.4917671Z #  ------------------------------------------------------------
2020-10-22T10:44:32.4918016Z   
2020-10-22T10:44:32.4918251Z apiVersion: rbac.authorization.k8s.io/v1
2020-10-22T10:44:32.4918506Z kind: ClusterRoleBinding
2020-10-22T10:44:32.4918743Z metadata:
2020-10-22T10:44:32.4919155Z   name: dafdev-cluster-admins
2020-10-22T10:44:32.4919390Z roleRef:
2020-10-22T10:44:32.4919617Z   apiGroup: rbac.authorization.k8s.io
2020-10-22T10:44:32.4919873Z   kind: ClusterRole
2020-10-22T10:44:32.4920226Z   name: cluster-admin
2020-10-22T10:44:32.4920449Z subjects:
2020-10-22T10:44:32.4920770Z   - kind: Group
2020-10-22T10:44:32.4921217Z     name: 4b1aacd9-****-****-8e55-4fc9f94c69bc
2020-10-22T10:44:32.4921563Z ---
2020-10-22T10:44:32.4921812Z apiVersion: rbac.authorization.k8s.io/v1
2020-10-22T10:44:32.4922066Z kind: ClusterRoleBinding
2020-10-22T10:44:32.4922282Z metadata:
2020-10-22T10:44:32.4922616Z   name: dafdev-admin
2020-10-22T10:44:32.4922834Z roleRef:
2020-10-22T10:44:32.4923060Z   apiGroup: rbac.authorization.k8s.io
2020-10-22T10:44:32.4923317Z   kind: ClusterRole
2020-10-22T10:44:32.4923532Z   name: admin
2020-10-22T10:44:32.4923715Z subjects:
2020-10-22T10:44:32.4924055Z   - kind: Group
2020-10-22T10:44:32.4924489Z     name: f9f6419b-****-***-***-97b353ba1710
2020-10-22T10:44:32.4924857Z ---
2020-10-22T10:44:32.4925078Z apiVersion: rbac.authorization.k8s.io/v1
2020-10-22T10:44:32.4925347Z kind: ClusterRoleBinding
2020-10-22T10:44:32.4925549Z metadata:
2020-10-22T10:44:32.4925891Z   name: dafdev-view
2020-10-22T10:44:32.4926084Z roleRef:
2020-10-22T10:44:32.4926326Z   apiGroup: rbac.authorization.k8s.io
2020-10-22T10:44:32.4926564Z   kind: ClusterRole
2020-10-22T10:44:32.4926776Z   name: view
2020-10-22T10:44:32.4926956Z subjects:
2020-10-22T10:44:32.4927538Z   - kind: Group
2020-10-22T10:44:32.4927966Z     name: d41eb0f5-****-***-***-1939a3131a11
2020-10-22T10:44:32.4928329Z ---
2020-10-22T10:44:32.4928550Z apiVersion: rbac.authorization.k8s.io/v1
2020-10-22T10:44:32.4928821Z kind: ClusterRoleBinding
2020-10-22T10:44:32.4929021Z metadata:
2020-10-22T10:44:32.4929365Z   name: dafdev-edit
2020-10-22T10:44:32.4929580Z roleRef:
2020-10-22T10:44:32.4929804Z   apiGroup: rbac.authorization.k8s.io
2020-10-22T10:44:32.4930172Z   kind: ClusterRole
2020-10-22T10:44:32.4930368Z   name: edit
2020-10-22T10:44:32.4931179Z subjects:
2020-10-22T10:44:32.4931569Z   - kind: Group
2020-10-22T10:44:37.9202469Z     name: b89b53c8-****-****-8176-22f4b12592f5clusterrolebinding.rbac.authorization.k8s.io/dafdev-cluster-admins created
2020-10-22T10:44:42.9686928Z clusterrolebinding.rbac.authorization.k8s.io/dafdev-admin created
2020-10-22T10:44:48.0081291Z clusterrolebinding.rbac.authorization.k8s.io/dafdev-view created
2020-10-22T10:44:53.0483770Z clusterrolebinding.rbac.authorization.k8s.io/dafdev-edit created

I reverified the complete script in new deployment and in last it's coming as cluster role binding created. I will try to find out why it's not working even if we can see values in the group...(i just masked *** from the actual group id). 
and why its working after manually applying the file. Thank you again for your help.
